"use client";

import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, CreditCard, MapPin, PackageCheck, Phone, ReceiptText, Truck } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { managementService } from "@/modules/operations/api/management.service";
import { DataState, StatusBadge } from "@/modules/operations/components/management-ui";
import type { DashboardRole, OrderManagementDetail } from "@/modules/operations/types/operations.type";
import { Button } from "@/shared/components/ui/button";
import { formatCurrency, productImageUrl } from "@/shared/utils/format";
import { formatStatus } from "@/shared/utils/status";

const dateTime = (value?: string | null) => value ? new Intl.DateTimeFormat("vi-VN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "Chưa ghi nhận";
const shortId = (id: string) => id.slice(0, 8).toUpperCase();
const methodLabels: Record<string, string> = { CashOnDelivery: "Thanh toán khi nhận hàng", BankTransfer: "Chuyển khoản ngân hàng", VnPay: "VNPay", Momo: "MoMo", Manual: "Thủ công" };
const paymentLabels: Record<string, string> = { Pending: "Đang chờ", Succeeded: "Thành công", Failed: "Thất bại", Cancelled: "Đã hủy", Refunded: "Đã hoàn tiền" };

export function OrderManagementDetailView({ role, orderId }: Readonly<{ role: Extract<DashboardRole, "Admin" | "Manager">; orderId: string }>) {
  const [order, setOrder] = useState<OrderManagementDetail | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(null); try { setOrder(await managementService.getOrderDetail(orderId)); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Không tải được chi tiết đơn hàng."); } finally { setLoading(false); } }, [orderId]);
  useEffect(() => { void load(); }, [load]);
  return <DataState loading={loading} error={error} empty={!order}>{order && <OrderDetail order={order} role={role} />}</DataState>;
}

function OrderDetail({ order, role }: Readonly<{ order: OrderManagementDetail; role: Extract<DashboardRole, "Admin" | "Manager"> }>) {
  const delivered = order.shipments.filter((shipment) => shipment.status === "Delivered").length;
  return <div className="mx-auto max-w-6xl"><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><Button asChild variant="ghost" className="-ml-3 text-slate-600"><Link href={`/${role.toLowerCase()}/orders`}><ArrowLeft className="size-4" />Quay lại đơn hàng</Link></Button><p className="text-xs font-semibold text-slate-400">Tạo lúc {dateTime(order.createdAt)}</p></div>
    <header className="relative overflow-hidden rounded-2xl bg-[#07111f] px-6 py-7 text-white shadow-[0_18px_45px_rgba(7,17,31,.18)] sm:px-8"><div className="absolute -right-16 -top-24 size-64 rounded-full border border-cyan-200/15" /><div className="relative flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[11px] font-black tracking-[.16em] text-cyan-300">{role.toUpperCase()} / ORDER DETAIL</p><h1 className="mt-2 text-3xl font-black tracking-[-.045em]">Đơn hàng <span className="font-mono text-cyan-300">#{shortId(order.id)}</span></h1><p className="mt-2 text-sm text-slate-300">{order.items.length} dòng hàng · {order.shipments.length} kiện vận chuyển · Tổng {formatCurrency(order.totalAmount)}</p></div><StatusBadge value={order.status} /></div></header>
    <div className="mt-6 grid gap-6 lg:grid-cols-[minmax(0,1.35fr)_minmax(300px,.85fr)]"><div className="grid gap-6"><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-[0_10px_28px_rgba(15,32,55,.05)]"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4 sm:px-6"><div><p className="text-[11px] font-black tracking-[.13em] text-cyan-700">HÀNG HÓA TRONG ĐƠN</p><h2 className="mt-1 font-black text-slate-900">Giá đã chốt khi đặt hàng</h2></div><PackageCheck className="size-6 text-cyan-600" /></div><div className="divide-y divide-slate-100">{order.items.map((item) => <div key={item.productId} className="flex gap-4 px-5 py-4 sm:px-6"><Image src={item.thumbnailUrl ? productImageUrl(item.thumbnailUrl) : "/brand/AnhEcommerc.png"} alt="" width={56} height={56} unoptimized className="size-14 rounded-xl border border-slate-100 object-cover" /><div className="min-w-0 flex-1"><h3 className="truncate text-sm font-bold text-slate-800">{item.productName}</h3><p className="mt-1 text-xs text-slate-400">Mã SP: <span className="font-mono">{shortId(item.productId)}</span> · {formatCurrency(item.unitPrice)}</p></div><div className="self-center text-right"><p className="text-sm font-black tabular-nums text-slate-800">{formatCurrency(item.lineTotal)}</p><p className="mt-1 text-xs font-bold text-slate-400">× {item.quantity}</p></div></div>)}</div><div className="flex items-center justify-between bg-slate-50 px-5 py-4 sm:px-6"><span className="font-bold text-slate-600">Tổng thanh toán</span><strong className="text-xl font-black tabular-nums tracking-[-.03em] text-slate-950">{formatCurrency(order.totalAmount)}</strong></div></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_10px_28px_rgba(15,32,55,.05)]"><div className="flex items-center justify-between"><div><p className="text-[11px] font-black tracking-[.13em] text-cyan-700">CÁC KIỆN VẬN CHUYỂN</p><h2 className="mt-1 font-black text-slate-900">{order.shipments.length ? `${delivered}/${order.shipments.length} kiện đã giao` : "Chưa tạo shipment"}</h2></div><Truck className="size-6 text-cyan-600" /></div><div className="mt-5 grid gap-3">{order.shipments.map((shipment) => <article key={shipment.id} className="rounded-xl border border-slate-100 bg-slate-50/70 p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-mono text-sm font-black text-slate-800">#{shortId(shipment.id)}</p><p className="mt-1 text-xs text-slate-500">{shipment.itemCount} sản phẩm · {shipment.shippingProvider ?? "Chưa bàn giao"}</p></div><StatusBadge value={shipment.status} /></div>{shipment.trackingNumber && <p className="mt-3 border-t border-slate-200 pt-3 text-xs text-slate-500">Mã vận đơn <span className="ml-1 font-mono font-bold text-slate-700">{shipment.trackingNumber}</span></p>}</article>)}{!order.shipments.length && <p className="rounded-xl bg-slate-50 px-4 py-5 text-center text-sm text-slate-500">Đơn này chưa có kiện vận chuyển.</p>}</div></section></div>
      <div className="grid content-start gap-6"><section className="rounded-2xl border border-cyan-100 bg-gradient-to-br from-cyan-50 to-white p-5 shadow-[0_10px_28px_rgba(8,145,178,.07)]"><div className="flex gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl rounded-bl-md bg-cyan-600 text-white"><MapPin className="size-5" /></span><div className="min-w-0"><p className="text-[11px] font-black tracking-[.13em] text-cyan-700">NGƯỜI NHẬN</p><h2 className="mt-1 text-lg font-black text-slate-900">{order.delivery.recipientName ?? "Chưa có tên người nhận"}</h2><p className="mt-1 flex items-center gap-2 text-sm font-medium text-slate-600"><Phone className="size-4 text-cyan-700" />{order.delivery.recipientPhone ?? "Chưa có số điện thoại"}</p><p className="mt-4 text-sm leading-6 text-slate-700">{order.delivery.shippingAddress ?? "Chưa có địa chỉ giao hàng"}</p>{order.delivery.deliveryNote && <p className="mt-3 rounded-lg border border-cyan-100 bg-white/80 px-3 py-2 text-sm text-slate-600"><span className="font-bold text-slate-700">Ghi chú: </span>{order.delivery.deliveryNote}</p>}</div></div></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_10px_28px_rgba(15,32,55,.05)]"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl rounded-bl-md bg-slate-900 text-cyan-300"><CreditCard className="size-5" /></span><div><p className="text-[11px] font-black tracking-[.13em] text-cyan-700">THANH TOÁN</p><h2 className="font-black text-slate-900">{order.payments.length ? `${order.payments.length} giao dịch` : "Chưa khởi tạo"}</h2></div></div><div className="mt-5 grid gap-3">{order.payments.map((payment) => <div key={payment.id} className="rounded-xl bg-slate-50 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-bold text-slate-800">{methodLabels[payment.method] ?? payment.method}</p><p className="mt-1 text-xs text-slate-500">{dateTime(payment.paidAt ?? payment.createdAt)}</p></div><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[11px] font-bold text-emerald-700">{paymentLabels[payment.status] ?? payment.status}</span></div>{payment.transactionId && <p className="mt-3 border-t border-slate-200 pt-3 text-xs text-slate-500">Mã GD <span className="ml-1 font-mono font-bold text-slate-700">{payment.transactionId}</span></p>}</div>)}{!order.payments.length && <p className="rounded-xl bg-slate-50 px-4 py-5 text-center text-sm text-slate-500">Chưa có thông tin thanh toán.</p>}</div></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_10px_28px_rgba(15,32,55,.05)]"><div className="flex items-center gap-3"><ReceiptText className="size-5 text-cyan-700" /><h2 className="font-black text-slate-900">Mốc đơn hàng</h2></div><ol className="mt-5 grid gap-4 text-sm"><li><p className="font-bold text-slate-800">Đơn được tạo</p><p className="mt-1 text-xs text-slate-400">{dateTime(order.createdAt)}</p></li><li><p className="font-bold text-slate-800">Trạng thái hiện tại</p><p className="mt-1 text-xs text-slate-500">{formatStatus(order.status)}</p></li>{order.payments.some((payment) => payment.paidAt) && <li><p className="font-bold text-slate-800">Thanh toán thành công</p><p className="mt-1 text-xs text-slate-400">{dateTime(order.payments.find((payment) => payment.paidAt)?.paidAt)}</p></li>}</ol></section></div></div></div>;
}
